name: Release Docker Image

on:
  release:
    types: [published]  # 当有新的 Release 发布时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout tag code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from release tag
        id: extract_version
        run: |
          RAW_TAG=${GITHUB_REF##*/}
          VERSION=${RAW_TAG#n8n@}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Build and push multi-arch Docker images
        run: |
          # 构建并直接推送 multi-arch 镜像（amd64 + arm64）
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=$RELEASE_VERSION \
            -t blowsnow/n8n-chinese:$RELEASE_VERSION \
            -t blowsnow/n8n-chinese:latest \
            --push \
            .
